source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'coffee-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'sass-rails'
gem 'sqlite3'
gem 'uglifier'

gem 'hamlit', path: '../..'

group :development, :test do
  gem 'pry-rails'
  gem 'spring'
  gem 'rspec-rails', '>= 3.2'
end

