$:.unshift File.expand_path('../../../lib', __FILE__)

require 'json'

desc 'Convert tests.json into rspec tests'
task :convert do
  spec =  "describe 'haml-spec' do\n"
  spec += "  def assert_render(html, haml, locals, options)\n"
  spec += "    engine = Hamlit::Template.new(options) { haml }\n"
  spec += "    result = engine.render(Object.new, locals)\n"
  spec += "    expect(result.strip).to eq(html)\n"
  spec += "  end\n\n"

  contexts = JSON.parse(File.read(File.expand_path('../../../haml-spec/tests.json', __FILE__)))
  contexts.each_with_index do |context, index|
    spec += "\n" if index != 0
    spec += "  context \"#{context[0]}\" do\n"

    tests = []
    context[1].each do |name, test|
      tests << {
        name: name,
        html: test['html'],
        haml: test['haml'],
        locals: test['locals'],
        config: test['config'],
      }
    end

    spec += tests.map { |test|
      locals  = Hash[(test[:locals] || {}).map {|x, y| [x.to_sym, y]}]
      options = Hash[(test[:config] || {}).map {|x, y| [x.to_sym, y]}]
      options[:format] = options[:format].to_sym if options[:format]

      spec =  "    specify \"#{test[:name]}\" do\n"
      spec += "      html    = %q{#{test[:html]}}\n"
      spec += "      haml    = %q{#{test[:haml]}}\n"
      spec += "      locals  = #{locals}\n"
      spec += "      options = #{options}\n"
      spec += "      assert_render(html, haml, locals, options)\n"
      spec += "    end\n"
    }.join("\n")
    spec += "  end\n"
  end

  spec += "end\n"
  File.write('ruby_haml_spec.rb', spec)
end

task default: :convert
