source 'https://rubygems.org'

gem 'rails', '~> 4.2'

gem 'coffee-rails', '~> 4.1.0'
gem 'hamlit', path: '../../'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
